app:
  # image base
  #   image: ubuntu
  # build base
  #   build: path/to/dockerfile_dir
  build: Rakefile.d/container/app
  volumes:
    - volumes/app:/app
  working_dir: /app
  # keep running
  command: "tail -f /dev/null"
